### ISSUE TITLE
Predicates should be AND by default

### ISSUE THREAD

**Issue by markostojanovic087** [apuigsech/rest-layer-sql#3]
When I was sending http DELETE requests on nested resource path
(_e.g. localhost:8080/api/users/userid/records/recordid_)
I got response saying that SQL query is not right.

I debug the queries and saw that they were formed like:
_SELECT * FROM record WHERE id LIKE recordid iduser LIKE userid_
The AND word was missing.

I searched through the [rest-layer](https://github.com/rs/rest-layer) code and found that AND is never added to predicate.

In order to have a workaround I made a nasty hack in [routing.go](https://github.com/rs/rest-layer/blob/master/rest/routing.go)
```
// Query builds a query object from the matched route
func (r *RouteMatch) Query() (*query.Query, *Error) {

	qp := queryParser{rsc: r.Resource()}
	if qp.rsc == nil {
		return nil, &Error{500, "missing resource", nil}
	}

	//TODO : HACK
	doit := false
	// Append route fields to the query
	for _, rp := range r.ResourcePath {
		if rp.Value != nil {
			log.Print("routing APENDUJEM EQUAL")
			if doit {
				qp.q.Predicate = append(qp.q.Predicate, &query.And{})
			} else {
				doit = true
			}

			qp.q.Predicate = append(qp.q.Predicate, &query.Equal{Field: rp.Field, Value: rp.Value})
		}
	}
```

In order to form a sql query properly I also had to change a [query.go](https://github.com/apuigsech/rest-layer-sql/blob/master/query.go).

Not sure if it is relevant, but what I did there is
```
func translatePredicate(q query.Predicate) (sqlQuery string, sqlParams []interface{}, err error) {
	log.Print(q)
	for _, exp := range q {
		switch t := exp.(type) {
		case *query.And:
			//TODO : HACK
			log.Print("Expression type AND")
			/*var s string
			for _, subExp := range *t {
				log.Print("count")
				sb, extraSqlParams, err := translatePredicate(query.Predicate{subExp})
				if err != nil {
					return "", []interface{}{}, err
				}
				sqlParams = append(sqlParams, extraSqlParams...)
				s += sb + " AND "
			}

			sqlQuery += "(" + s[:len(s)-5] + ")"*/

			sqlQuery += " AND " //Added this
```

First, I raised an issue on [rest-layer](https://github.com/rs/rest-layer) side [(Issue-245](https://github.com/rs/rest-layer/issues/245)) and as you can see the conclusion was that predicates should be AND by default and that It must be a bug in the sql storer.

Could you please read the [rest-layer](https://github.com/rs/rest-layer) side [(Issue-245](https://github.com/rs/rest-layer/issues/245) thread and tell me what do you think?

Thanks!

**Comment by mishak87** [comment]
@markostojanovic087 Hi I have demonstrated the bug in #4 using tests and proposed a fix.
